export const styles = {
  app: {
    fontFamily: "'Segoe UI', sans-serif",
    minHeight: "100vh",
    background: "#f5f5f0",
    color: "#2c2c2c",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 24px",
    background: "#2c3e50",
    color: "white",
    flexWrap: "wrap",
    gap: "10px",
  },
  logo: {
    fontSize: "18px",
    fontWeight: "bold",
  },
  navLinks: {
    display: "flex",
    gap: "4px",
  },
  navLink: {
    background: "transparent",
    border: "none",
    color: "#ffffffaa",
    padding: "8px 16px",
    cursor: "pointer",
    borderRadius: "6px",
    fontSize: "14px",
    transition: "all 0.2s",
  },
  navLinkActive: {
    background: "#ffffff22",
    color: "#ffffff",
    fontWeight: "600",
  },
  main: {
    maxWidth: "700px",
    margin: "0 auto",
    padding: "24px 16px",
  },
  pageTitle: {
    fontSize: "24px",
    marginBottom: "16px",
    borderBottom: "2px solid #2c3e50",
    paddingBottom: "8px",
  },
  text: {
    margin: "6px 0",
    lineHeight: "1.6",
  },
  card: {
    background: "white",
    borderRadius: "8px",
    padding: "20px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  form: {
    background: "white",
    borderRadius: "8px",
    padding: "20px",
    marginBottom: "20px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  input: {
    display: "block",
    width: "100%",
    padding: "10px 12px",
    marginBottom: "10px",
    border: "1px solid #ddd",
    borderRadius: "6px",
    fontSize: "14px",
    boxSizing: "border-box",
  },
  button: {
    background: "#2c3e50",
    color: "white",
    border: "none",
    padding: "10px 24px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },
  bookList: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  bookCard: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "white",
    padding: "14px 18px",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    flexWrap: "wrap",
    gap: "6px",
  },
  bookAuthor: {
    color: "#666",
    fontSize: "14px",
  },
  bookYear: {
    background: "#eee",
    padding: "3px 10px",
    borderRadius: "12px",
    fontSize: "13px",
  },
};
